export const PERMISSION_GROUPS = [
  'Dashboard',
  'Users',
  'Staff',
  'Roles',
  'Permissions',
  'Products',
  'Categories',
  'Brands',
  'Attributes',
  'Inventory',
  'Warehouses',
  'Orders',
  'Payments',
  'Refunds',
  'Customers',
  'Reports',
  'Analytics',
  'Marketing',
  'Coupons',
  'Offers',
  'Campaigns',
  'CMS',
  'Banners',
  'Reviews',
  'Notifications',
  'AuditLogs',
  'Settings',
  'BusinessSettings',
  'Integrations',
  'Shipping',
  'Tax',
  'Delivery',
  'AI',
  'Import',
  'Export',
] as const;

// ponytail: standardized CRUD actions for permission codes — add per-module as seeded permissions
export const PERMISSION_ACTIONS = [
  'view',
  'create',
  'update',
  'delete',
  'approve',
  'export',
  'import',
  'manage',
] as const;
