export const INITIAL_PROFILES = [
  {
    id: "react-production-base",
    name: "React Production Base",
    description: "Standard baseline rules for any React compilation build target.",
    parentProfileId: null,
    version: "v1.0.0",
    status: "Active",
    category: "Base Framework",
    createdAt: "2026-01-10T12:00:00Z",
    updatedAt: "2026-06-15T09:30:00Z"
  },
  {
    id: "boutique-standard-profile",
    name: "Boutique Standard Profile",
    description: "Retail and E-commerce specific rules inheriting React Production Base.",
    parentProfileId: "react-production-base",
    version: "v1.1.0",
    status: "Active",
    category: "Business Verticals",
    createdAt: "2026-02-14T08:00:00Z",
    updatedAt: "2026-06-20T14:45:00Z"
  },
  {
    id: "luxury-boutique-profile",
    name: "Luxury Boutique Profile",
    description: "Strictest guidelines tailored for premium boutique brands.",
    parentProfileId: "boutique-standard-profile",
    version: "v1.0.0",
    status: "Draft",
    category: "Luxury Tier",
    createdAt: "2026-06-25T11:00:00Z",
    updatedAt: "2026-06-28T16:00:00Z"
  }
];

export const INITIAL_RULES = [
  // 1. PROJECT STRUCTURE
  {
    id: "rule-src-components-folder",
    category: "Project Structure",
    name: "Mandatory src/components Folder",
    description: "Verify that reusable UI files reside inside src/components.",
    severity: "Required",
    validationType: "Folder Structure",
    aiStrategy: "Move Folder",
    autofix: "Yes",
    futureModule: "Validation Engine",
    whyExists: "Enforces neat organization of visual primitives across developer workspaces.",
    howValidate: "Recursively scans files checking if UI nodes sit in root instead of components folder.",
    howFix: "Creates src/components/ directory and moves stateless presentation elements there.",
    badExample: "src/Logo.jsx (root components violate structure rules)",
    goodExample: "src/components/Logo.jsx (correct path schema mapping)",
    createdVersion: "v1.0.0",
    lastUpdatedVersion: "v1.0.0",
    changeNotes: "Initial check baseline rules release.",
    profileId: "react-production-base",
    sourceProfileId: "react-production-base",
    overrideState: "Inherited" // 'Inherited' | 'Overridden' | 'Custom'
  },
  {
    id: "rule-package-json-exists",
    category: "Project Structure",
    name: "Manifest package.json Presence",
    description: "Verify package.json sits in root folder for dependency resolving.",
    severity: "Required",
    validationType: "File Exists",
    aiStrategy: "Create Missing File",
    autofix: "No",
    futureModule: "Upload Website",
    whyExists: "Crucial for running node package resolver and sandbox compiler audits.",
    howValidate: "Checks directory root path for package.json.",
    howFix: "Prompts developer to initialize NPM environment before uploading.",
    badExample: "No package.json file exists (NPM package audits fail immediately)",
    goodExample: "package.json exists with name and dependencies properties",
    createdVersion: "v1.0.0",
    lastUpdatedVersion: "v1.0.0",
    changeNotes: "Core build prerequisite scanner rule.",
    profileId: "react-production-base",
    sourceProfileId: "react-production-base",
    overrideState: "Inherited"
  },

  // 2. TECHNOLOGY STACK
  {
    id: "rule-react-vite-bundler",
    category: "Technology Stack",
    name: "React + Vite Compiler Setup",
    description: "Requires Vite config declarations for lightning fast compiles.",
    severity: "Required",
    validationType: "Package Analysis",
    aiStrategy: "Generate Config",
    autofix: "Partial",
    futureModule: "Validation Engine",
    whyExists: "Ensures template projects use modern tooling that compiles cleanly.",
    howValidate: "Inspects package.json dependencies for 'vite' and '@vitejs/plugin-react'.",
    howFix: "Appends plugins and updates compile scripts inside package.json config files.",
    badExample: "\"scripts\": { \"dev\": \"react-scripts start\" } (Legacy CRA configuration)",
    goodExample: "\"scripts\": { \"dev\": \"vite\" } (Compliant bundle rules setup)",
    createdVersion: "v1.0.0",
    lastUpdatedVersion: "v1.0.1",
    changeNotes: "Upgraded bundler rule to support newer Vite 5 specifications.",
    profileId: "react-production-base",
    sourceProfileId: "react-production-base",
    overrideState: "Inherited"
  },

  // 3. CODING STANDARDS
  {
    id: "rule-no-inline-styles",
    category: "Coding Standards",
    name: "No Inline Styles allowed",
    description: "Convert CSS attributes into Tailwind utility class strings.",
    severity: "Required",
    validationType: "AST Analysis",
    aiStrategy: "Convert CSS",
    autofix: "Yes",
    futureModule: "AI Certification",
    whyExists: "Guarantees visual consistency and responsive breakpoint overrides function.",
    howValidate: "Scans AST tree finding JSX elements style={{ ... }} configurations.",
    howFix: "Translates stylesheet key-value properties into corresponding Tailwind utility strings.",
    badExample: "<div style={{ color: 'red', marginTop: '10px' }} />",
    goodExample: "<div className=\"text-red-500 mt-2.5\" />",
    createdVersion: "v1.0.0",
    lastUpdatedVersion: "v1.0.0",
    changeNotes: "Initial check baseline rules release.",
    profileId: "react-production-base",
    sourceProfileId: "react-production-base",
    overrideState: "Inherited"
  },

  // 4. COMPONENT STANDARDS
  {
    id: "rule-atomic-structure",
    category: "Component Standards",
    name: "Atomic Component Design Patterns",
    description: "Requires division between layout wrappers, containers, and visual widgets.",
    severity: "Recommended",
    validationType: "AST Analysis",
    aiStrategy: "Generate Component",
    autofix: "No",
    futureModule: "AI Certification",
    whyExists: "Prevents monolithic files and encourages reusable components codebases.",
    howValidate: "Lints component size and loops warning on files exceeding 400 lines.",
    howFix: "Suggests breaking down giant visual trees into smaller sub-components.",
    badExample: "One single file containing header, list, card details, modal, and footer code.",
    goodExample: "Imports reusable elements like Header, Sidebar, and card grid widgets.",
    createdVersion: "v1.1.0",
    lastUpdatedVersion: "v1.1.0",
    changeNotes: "Added to improve developer template readability.",
    profileId: "boutique-standard-profile",
    sourceProfileId: "boutique-standard-profile",
    overrideState: "Custom"
  },

  // 5. UI/UX STANDARDS
  {
    id: "rule-dark-mode-ready",
    category: "UI/UX Standards",
    name: "Dark Mode Utility Classes",
    description: "Requires responsive dark variants to prevent layout flashes.",
    severity: "Recommended",
    validationType: "Regex",
    aiStrategy: "Convert CSS",
    autofix: "Partial",
    futureModule: "AI Certification",
    whyExists: "Ensures seamless theme switching for high-end boutique storefronts.",
    howValidate: "Lints if styling strings contain 'dark:' counterparts on background/text rules.",
    howFix: "Appends default gray dark class states next to standard white colors.",
    badExample: "<div className=\"bg-white text-gray-900\" />",
    goodExample: "<div className=\"bg-white dark:bg-gray-950 text-gray-900 dark:text-gray-50\" />",
    createdVersion: "v1.0.0",
    lastUpdatedVersion: "v1.1.0",
    changeNotes: "Promoted to Recommended in Boutique profile (was Optional in React base).",
    profileId: "boutique-standard-profile",
    sourceProfileId: "react-production-base",
    overrideState: "Overridden"
  },

  // 6. API STANDARDS
  {
    id: "rule-api-timeout-limit",
    category: "API Standards",
    name: "Mandatory Request Timeouts",
    description: "All api client calls must specify a maximum timeout limit parameter.",
    severity: "Required",
    validationType: "AST Analysis",
    aiStrategy: "Replace Code",
    autofix: "Yes",
    futureModule: "Validation Engine",
    whyExists: "Prevents UI freezing and browser lockouts on dead server ports.",
    howValidate: "Scans axios/fetch configurations looking for timeout key constraints.",
    howFix: "Appends a default 10000ms timeout value inside API configuration objects.",
    badExample: "axios.get('/api/products') (unrestricted timeout hazard)",
    goodExample: "axios.get('/api/products', { timeout: 10000 }) (safe request wrapper)",
    createdVersion: "v1.0.0",
    lastUpdatedVersion: "v1.0.0",
    changeNotes: "Core reliability compliance checker rule.",
    profileId: "react-production-base",
    sourceProfileId: "react-production-base",
    overrideState: "Inherited"
  },

  // 7. CMS STANDARDS
  {
    id: "rule-cms-brand-logo",
    category: "CMS Standards",
    name: "CMS Logo Dimension Constraints",
    description: "Header logo elements must contain width and height restrictions.",
    severity: "Required",
    validationType: "AST Analysis",
    aiStrategy: "Replace Code",
    autofix: "Yes",
    futureModule: "AI Certification",
    whyExists: "Prevents large uploaded tenant files from breaking visual layout dimensions.",
    howValidate: "Locates logo image nodes and checks for fixed aspect-ratio parameters.",
    howFix: "Forces max-width and object-contain classes on header logo image tags.",
    badExample: "<img src={logoUrl} alt=\"Boutique Logo\" /> (dangerous size risk)",
    goodExample: "<img src={logoUrl} className=\"h-12 w-auto object-contain\" alt=\"Boutique Logo\" />",
    createdVersion: "v1.1.0",
    lastUpdatedVersion: "v1.1.0",
    changeNotes: "Initial check baseline rules release.",
    profileId: "boutique-standard-profile",
    sourceProfileId: "boutique-standard-profile",
    overrideState: "Custom"
  },

  // 8. SECURITY STANDARDS
  {
    id: "rule-no-secrets-allowed",
    category: "Security Standards",
    name: "Block Embedded Secrets & API Keys",
    description: "Scans project code files to detect keys, tokens, or credential leaks.",
    severity: "Required",
    validationType: "Security Scan",
    aiStrategy: "Generate Config",
    autofix: "No",
    futureModule: "Validation Engine",
    whyExists: "Critical security rule preventing credentials compromise in static assets.",
    howValidate: "Runs regex checks matching key patterns (e.g. sk-..., AIzaSy...) across codebase.",
    howFix: "Alerts developer and replaces secret values with process.env variables.",
    badExample: "const API_KEY = \"AIzaSyB38491c9201fcd...\" (leaked secret)",
    goodExample: "const API_KEY = import.meta.env.VITE_API_KEY (safe reference)",
    createdVersion: "v1.0.0",
    lastUpdatedVersion: "v1.0.0",
    changeNotes: "Strict compliance block. Fails build on discovery.",
    profileId: "react-production-base",
    sourceProfileId: "react-production-base",
    overrideState: "Inherited"
  },

  // 9. PERFORMANCE STANDARDS
  {
    id: "rule-image-lazy-loading",
    category: "Performance Standards",
    name: "Image Lazy Loading Attribute",
    description: "Non-critical image elements must use loading='lazy' parameter.",
    severity: "Recommended",
    validationType: "AST Analysis",
    aiStrategy: "Replace Code",
    autofix: "Yes",
    futureModule: "Prompt Generator",
    whyExists: "Saves mobile data bandwidth and improves page loading speeds.",
    howValidate: "Inspects img tags outside hero visual areas checking loading key.",
    howFix: "Automatically appends loading=\"lazy\" to static image tags.",
    badExample: "<img src=\"product.jpg\" /> (loads immediately, blocking thread)",
    goodExample: "<img src=\"product.jpg\" loading=\"lazy\" /> (defer load support)",
    createdVersion: "v1.0.0",
    lastUpdatedVersion: "v1.0.0",
    changeNotes: "Core performance check rule.",
    profileId: "react-production-base",
    sourceProfileId: "react-production-base",
    overrideState: "Inherited"
  },

  // 10. SEO STANDARDS
  {
    id: "rule-metadata-check",
    category: "SEO Standards",
    name: "Dynamic Document Metadata",
    description: "Stores and updates document title, description, and Open Graph tags.",
    severity: "Required",
    validationType: "SEO Scan",
    aiStrategy: "Create Meta Tags",
    autofix: "Yes",
    futureModule: "Prompt Generator",
    whyExists: "Ensures boutique stores index correctly on search engines and social platforms.",
    howValidate: "Lints index.html or React Helmet tags for presence of description and title tags.",
    howFix: "Appends required metadata definitions into HTML head dynamically.",
    badExample: "<head><title>Vite App</title></head> (Generic title, no metadata description)",
    goodExample: "<head><title>Tiny Tucks Boutique</title><meta name=\"description\" content=\"...\" /></head>",
    createdVersion: "v1.0.0",
    lastUpdatedVersion: "v1.0.0",
    changeNotes: "Core SEO index requirement.",
    profileId: "react-production-base",
    sourceProfileId: "react-production-base",
    overrideState: "Inherited"
  },

  // 11. ACCESSIBILITY STANDARDS
  {
    id: "rule-img-alt-text",
    category: "Accessibility Standards",
    name: "Image Alternative Text Attribute",
    description: "Requires descriptive alt text on all graphic and icon assets.",
    severity: "Required",
    validationType: "Accessibility Scan",
    aiStrategy: "Create Meta Tags",
    autofix: "Partial",
    futureModule: "AI Certification",
    whyExists: "Strict WCAG standard for blind users navigating via screen readers.",
    howValidate: "Finds img nodes lacking descriptive text values or non-empty alt keys.",
    howFix: "Uses AI agent to generate alt labels describing image visuals.",
    badExample: "<img src=\"logo.png\" /> (empty or missing alt tags)",
    goodExample: "<img src=\"logo.png\" alt=\"VS Boutique Brand logo logo-image\" />",
    createdVersion: "v1.0.0",
    lastUpdatedVersion: "v1.0.0",
    changeNotes: "WCAG A11y compliance validator rule.",
    profileId: "react-production-base",
    sourceProfileId: "react-production-base",
    overrideState: "Inherited"
  },

  // 12. DEPLOYMENT STANDARDS
  {
    id: "rule-clean-build-verification",
    category: "Deployment Standards",
    name: "Production Build Command Check",
    description: "Ensures package configs support 'npm run build' compiling static files.",
    severity: "Required",
    validationType: "Bundle Analysis",
    aiStrategy: "Optimize Bundle",
    autofix: "No",
    futureModule: "Deployment",
    whyExists: "Verifies compiler is error-free before CDN deployment occurs.",
    howValidate: "Checks package.json file scripting entries for build command strings.",
    howFix: "Prompts developer to repair compilation logs.",
    badExample: "\"build\": \"webpack --config bad-config.js\" (compilation failures block CDN)",
    goodExample: "\"build\": \"vite build\" (correct static build compiler scripts)",
    createdVersion: "v1.0.0",
    lastUpdatedVersion: "v1.0.0",
    changeNotes: "Deployment release gate rule.",
    profileId: "react-production-base",
    sourceProfileId: "react-production-base",
    overrideState: "Inherited"
  }
];
